### ISSUE TITLE
Adopt a Contributor License Agreement?

### ISSUE THREAD

**Issue by ddbeck** [web-platform-dx/feature-set#276]
This repo doesn't (explicitly) have a contributor license agreement (CLA) incorporated into it. The main question is this: **should we have a CLA or refer to an existing one? Or is it unnecessary?**

This issue was prompted by a question from the interim governance group. Our inspiration, [the BCD governance doc](https://github.com/mdn/browser-compat-data/blob/main/GOVERNANCE.md), makes mention of the Mozilla Community Participation Guidelines and Mozilla Commit Access Policy. While the W3C [CEPC](https://www.w3.org/Consortium/cepc/) is an obvious drop-in replacement for the Mozilla CPG, it's not clear whether or what must replace the Commit Access Policy.

I tried looking at other WebDX and W3C project repos (specifically those which are _not_ specifications) for hints on how to handle this and I didn't learn anything useful (or at least, recognizably useful to me).

Here are a few things I know:

- The [`LICENSE.txt`](https://github.com/web-platform-dx/feature-set/blob/09bc0b4f044306fb33076bc271b409c1aa9f7ff7/packages/web-features/LICENSE.txt) file (APL 2.0) creates some CLA-like expectations (e.g., contributors grant a license to use contributions to the project). (As an aside, we should probably promote this file to the top of the repo, so it's more obvious what license we're operating under.)
- There's no separate CLA _in_ this repository.
- The W3C has a [CLA](https://www.w3.org/community/about/process/cla/) and members of the WebDX have necessarily agreed to it (i.e., it's a condition of membership).

But there are some things which are unclear to me:

- Does contributing to this (or any other WebDX) repo cause agreement with the W3C CLA? If so, should we mention that somewhere (e.g., in a `CONTRIBUTORS` file)?
- If the W3C CLA doesn't apply, is the APL-2.0 license sufficient for contributors to understand how their contributions may be used?

NB: I'm not a lawyer. I'm approaching this more from a perspective of procedural familiarity: are we doing things in ways that are usual and typical and have we communicated what we're doing?

**Comment by ddbeck** [comment]
@tidoust, @dontcallmedom: Maybe you can provide some pointers-to-docs/guidance/input on this issue?

**Comment by tidoust** [comment]
The W3C Community License Agreement is much more targeted at contributions to specs than at contributions to open source projects. I don't think that we should try to apply it to this repository and require that contributors be WebDX Community Group participants, that would just seem to complicate things for no good reason.

We don't really have specific contributor license agreements for such open source projects in W3C. We usually just rely on the license. That also seems pretty usual to me in open source projects. What about adding a `CONTRIBUTING.md` file that mentions the license, similar to [the one used in Web Platform Tests](https://github.com/web-platform-tests/wpt/blob/master/CONTRIBUTING.md)?

**Comment by ddbeck** [comment]
Thanks, @tidoust! That Web Platform Tests example works for me. I'll open a PR in the coming days to move the license file and do something rather like that contributing file.
